import db
from typing import List, Any, Dict


class Publisher:
    def __init__(self):
        self.table_name = "publisher"
        db.do_connect()
        self.create_table()

    def __del__(self):
        db.disconnect()

    def create_table(self) -> bool:
        query = f"""
        CREATE TABLE IF NOT EXISTS {self.table_name} (id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( START 1 ),
        CONSTRAINT {self.table_name}_id PRIMARY KEY (id), name TEXT NOT NULL, description TEXT);
        """
        try:
            db.cursor.execute(query)
            return True
        except db.Error as error:
            return False

    def add(self, name: str, description: str = "") -> bool:
        query = f"INSERT INTO {self.table_name} (name, description) VALUES (%s,%s)"
        try:
            db.cursor.execute(query, (name, description))
            return True
        except db.Error as error:
            return False

    def update(self, publisher_id: int, publisher_name: str, publisher_description: str) -> bool:
        query = f"UPDATE {self.table_name} SET name=%s,description=%s WHERE id=%s"
        try:
            db.cursor.execute(query, (publisher_name, publisher_description, publisher_id))
            return True
        except db.Error as error:
            return False

    def delete(self, publisher_id: int):
        query = f"DELETE FROM {self.table_name} WHERE id=%s"
        db.cursor.execute(query, (publisher_id,))
        return True

    def get(self, publisher_id:int) -> Dict:
        publisher_dict = {}
        query = f"SELECT * FROM {self.table_name} WHERE id=%s"
        try:
            db.cursor.execute(query,(publisher_id,))
            publisher: List[Any] = db.cursor.fetchone()
        except db.Error as error:
            return publisher_dict
        publisher_dict = {'id': publisher[0], 'name': publisher[1], 'description': publisher[2]}
        return publisher_dict

    def get_all(self) -> List:
        """ Get all of categories and return as a List """
        query = f"SELECT * FROM {self.table_name}"
        try:
            db.cursor.execute(query)
            publishers: List[Any] = db.cursor.fetchall()
        except db.Error as error:
            return []
        publishers_array = []
        for publisher in publishers:
            publisher_dict = {
                'id': publisher[0], 'name': publisher[1], 'description': publisher[2]
            }
            publishers_array.append(publisher_dict)
        return publishers_array

    def count(self) -> int:
        query = f"SELECT count(*) FROM {self.table_name}"
        db.cursor.execute(query)
        count = db.cursor.fetchone()[0]
        db.disconnect()
        return int(count)

    def exist(self, publisher_id: int) -> bool:
        query = f"SELECT COUNT (*) FROM {self.table_name} WHERE id=%s"
        db.cursor.execute(query, (publisher_id,))
        count = db.cursor.fetchone()[0]
        db.disconnect()
        return int(count) > 0
